theme = "windy"
languageCode = "en-us"
baseurl = "https://m3rcurylake.pages.dev/"
title = "M3rcuryLake"

author = "Ankit Mukherjee"


[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
